try{(function(g,p,m,h){function A(a){a=("; "+p.cookie).split("; "+a+"=");return 2==a.length?B(a.pop().split(";").shift()):""}function C(a){if(!v)return"";a=""+B(g.localStorage.getItem(a));a=a.split(";ex=");if(2==a.length&&0<a[1]){var c=new Date;c=c.valueOf();return c<=a[1]?a[0]:""}return a[0]}function r(a,c){var b=A(a);if("all"==c){var d=b;v&&(d=C(a));if(d==b)return b}else return b||C(a)||"";return""}function n(a,c){if("string"==typeof c){c=c.replace(/"/ig,"");var b=p.domain.split(".");if(1<b.length&&
c)for(var d="."+b[b.length-1],e=b.length-2;0<=e;e--){d="."+b[e]+d;var f=a,k=c,q=d;var w=new Date;w.setTime(w.getTime()+314496E5);p.cookie=f+"="+D(k)+(";expires="+w.toGMTString())+";path=/"+(q?";domain="+q:"")+";secure;SameSite=None";if(A(a)==c)break}b=c;d=0;v&&(e=["fosp_uid","fosp_aid","orig_aid","myvne_user_id"].indexOf(a),d=parseInt(d),0<d&&0>e&&(e=new Date,e.setTime(e.getTime()+1E3*d),e=e.valueOf(),b=b+";ex="+e),g.localStorage.setItem(a,D(b)))}}m=g._logForm||(g._logForm=[]);if(m.push===Array.prototype.push){var D=
function(a){try{return"function"==typeof encodeURIComponent?encodeURIComponent(a):escape(a)}catch(c){return a}},B=function(a){try{return"function"==typeof decodeURIComponent?decodeURIComponent(a):unescape(a)}catch(c){return a}},x="";x=(h=g.navigator)&&(h=h.userAgent)?h:"";var t=function(a){return-1!==x.toLowerCase().indexOf(a.toLowerCase())};try{g.localStorage.setItem("local_store","local_store");g.localStorage.removeItem("local_store");var u=!0}catch(a){u=!1}var v=u?1:0,E=function(){for(var a="",
c=0;16>c;c++)a+="abcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(36*Math.random()));c=/Mobile|iP(hone|od|ad)|Android|BlackBerry|IEMobile|Kindle|NetFront|Silk-Accelerated|(hpw|web)OS|Fennec|Minimo|Opera M(obi|ini)|Blazer|Dolfin|Dolphin|Skyfire|Zune/i.test(x)?"mob":t("iPad")||t("Android")&&!t("Mobile")||t("Silk")?"tab":"des";return a+"."+Math.floor((new Date).getTime()/1E3)+"."+c},F=function(a,c,b){return a.call.apply(a.bind,arguments)},G=function(a,c,b){if(!a)throw Error();if(2<arguments.length){var d=
Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(c,e)}}return function(){return a.apply(c,arguments)}},y=function(a,c,b){y=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?F:G;return y.apply(null,arguments)},H=function(a){var c=typeof a;if("object"==c)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return c;var b=Object.prototype.toString.call(a);
if("[object Window]"==b)return"object";if("[object Array]"==b||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==b||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==c&&"undefined"==typeof a.call)return"object";return c},l=function(a){return"string"==typeof a},I=function(a,
c,b){b=b||("https:"==document.location.protocol?"https":"http");return[b,"://",a,c].join("")},z=new function(){this.source_name="https://"+g.location.host;this.newU=E();this.fosp_uid=r("fosp_uid","any");this.fosp_aid=r("fosp_aid","any");this.orig_aid=r("orig_aid","any");this.myvne_user_id=r("myvne_user_id","any");this.urlRequest="https://la2.vnecdn.net/formadp";this.timeoutUser=0;this.syncCross=function(){var a=null,c;if(!a)a:{for(var b=[g.top],d,e=0;d=b[e++];)try{if(d.frames)for(var f=d.frames.length,
k=0;k<f&&1024>b.length;++k)b.push(d.frames[k])}catch(q){}for(f=0;f<b.length;f++)try{if(c=b[f].frames.eclick_lookup){a=c;break a}}catch(q){}a=null}if(a)a.postMessage(JSON.stringify({id:"int_sync_user",fosp_uid:this.fosp_uid,fosp_aid:this.fosp_aid,orig_aid:this.orig_aid,myvne_user_id:this.myvne_user_id}),"*");else if((c=p.getElementsByTagName("body"))&&c[0]){d=["fosp_aid="+this.fosp_aid,"orig_aid="+this.orig_aid,"fosp_uid="+this.fosp_uid,"myvne_user_id="+this.myvne_user_id];b=p.createElement("iframe");
d=I("adp.vnecdn.net/delivery/eclookup.html?"+d.join("&"),"");b.src=d;b.id="eclick_lookup";b.name="eclick_lookup";b.width=0;b.height=0;b.style.display="none";c[0].appendChild(b);b.onload=function(){a.postMessage(JSON.stringify({id:"int_sync_user",fosp_uid:this.fosp_uid,fosp_aid:this.fosp_aid,orig_aid:this.orig_aid,myvne_user_id:this.myvne_user_id}),"*")};try{a=b.contentWindow}catch(q){}}};this.setUserCross=function(a){try{var c=JSON.parse(a.data);if(c.id&&"sync_user_reply"==c.id){var b=c.fosp_uid||
"",d=c.fosp_aid||"",e=c.orig_aid||"";15<b.length&&33>b.length&&b!=this.fosp_uid&&(this.fosp_uid=b,n("fosp_uid",b));15<e.length&&33>e.length&&e!=this.orig_aid&&(this.orig_aid=e,n("orig_aid",e));9<d.length&&33>b.length&&d!=this.fosp_aid&&(this.fosp_aid=d,n("fosp_aid",d))}}catch(f){}};this.init=function(){var a=y(this.setUserCross,this);g.addEventListener?g.addEventListener("message",a,!1):g.attachEvent&&g.attachEvent("onmessage",a);15>this.fosp_uid.length&&(this.fosp_uid=this.newU,n("fosp_uid",this.fosp_uid));
15>this.orig_aid.length&&(this.orig_aid=this.newU,n("orig_aid",this.orig_aid));10>this.fosp_aid.length&&(this.fosp_aid=this.newU,n("fosp_aid",this.fosp_aid));this.syncCross()};this.sendRequest=function(a,c,b,d,e){4===arguments.length&&(e=d,d={});var f=new XMLHttpRequest;f.onerror=e;f.onreadystatechange=function(){if(4===f.readyState)return e(f.response)};for(var k in d)f.setRequestHeader(k,d[k]);"POST"==c?(f.open("POST",a,!0),f.send(JSON.stringify(b))):(f.open("GET",a,!0),f.send())};this.tracking=
function(a,c){c="function"==H(c)?c:function(){};a.campaign_name&&l(a.campaign_name)&&""!=a.campaign_name||console&&console.log("form tracking invalid data campaign_name",a);(!a.engagement_type||"number"!=typeof a.engagement_type||1>a.engagement_type)&&console&&console.log("form tracking invalid data evt_type",a);var b={fosp_aid:""+this.fosp_aid,orig_aid:""+this.orig_aid,fosp_uid:""+this.fosp_uid,myvne_user_id:""+this.myvne_user_id,source_type:a.source_type&&"external"==a.source_type?2:1,source_name:""+
this.source_name,campaign_name:""+a.campaign_name,engagement_type:""+a.engagement_type,evt_info:{}};a.index_brand&&l(a.index_brand)&&""!=a.index_brand&&(b.index_brand=a.index_brand);a.index_industrial&&l(a.index_industrial)&&""!=a.index_industrial&&(b.index_industrial=a.index_industrial);a.index_category&&l(a.index_category)&&""!=a.index_category&&(b.index_category=a.index_category);a.index_topic&&l(a.index_topic)&&""!=a.index_topic&&(b.index_topic=a.index_topic);a.evt_info&&null!==a.evt_info&&"object"===
typeof a.evt_info&&!Array.isArray(a.evt_info)&&(b.evt_info=a.evt_info);a.name&&l(a.name)&&""!=a.name&&(b.evt_info.name=a.name);a.email&&""!=a.email&&/\S+@\S+\.\S+/.test(a.email)&&(b.evt_info.email=a.email);a.age&&l(a.age)&&""!=a.age&&(b.evt_info.age=a.age);a.phone&&l(a.phone)&&""!=a.phone&&(b.evt_info.phone=a.phone);a.gender&&"number"==typeof a.gende&&0<a.gender&&3>a.gender&&(b.evt_info.gender=""+a.gender);this.sendRequest(this.urlRequest,"POST",b,{},c)}};z.init();if(m.push===Array.prototype.push){h=
0;for(u=m.length;h<u;++h)z.tracking(m[h]);m.push=function(a){z.tracking(a)}}}})(window,document,location,history)}catch(g){console.log("error:",g)};